
package Menu;
import Buddy.*;
import MejorAjuste.*;
import PrimerAjuste.*;
import SiguienteAjuste.*;
import java.awt.Color;

public class MenuE extends javax.swing.JFrame {
    
    /**
     * Variables de instancia para mover la ventana
     */
    int xMouse, yMouse;
    
    public MenuE(){

        initComponents();
        
        //Modificacion de ventana
        this.setLocationRelativeTo(null); //Que se coloque en el centro
        this.setResizable(false); //No pueda modificar el tamaño de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBuddy = new javax.swing.JPanel();
        txtBtnBuddy = new javax.swing.JLabel();
        btnMAjuste = new javax.swing.JPanel();
        txtBtnMajuste = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("memoria que desea observar");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 650, 100));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleccione el ajuste de gestión de ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 650, 100));

        btnBuddy.setBackground(new java.awt.Color(37, 150, 190));

        txtBtnBuddy.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtBtnBuddy.setForeground(new java.awt.Color(255, 255, 255));
        txtBtnBuddy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnBuddy.setText("Buddy");
        txtBtnBuddy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBtnBuddy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnBuddyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnBuddyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnBuddyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuddyLayout = new javax.swing.GroupLayout(btnBuddy);
        btnBuddy.setLayout(btnBuddyLayout);
        btnBuddyLayout.setHorizontalGroup(
            btnBuddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnBuddy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        btnBuddyLayout.setVerticalGroup(
            btnBuddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnBuddy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel4.add(btnBuddy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, 100));

        btnMAjuste.setBackground(new java.awt.Color(37, 150, 190));

        txtBtnMajuste.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtBtnMajuste.setForeground(new java.awt.Color(255, 255, 255));
        txtBtnMajuste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnMajuste.setText("Mejor Ajuste");
        txtBtnMajuste.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBtnMajuste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnMajusteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnMajusteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnMajusteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMAjusteLayout = new javax.swing.GroupLayout(btnMAjuste);
        btnMAjuste.setLayout(btnMAjusteLayout);
        btnMAjusteLayout.setHorizontalGroup(
            btnMAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnMajuste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        btnMAjusteLayout.setVerticalGroup(
            btnMAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnMajuste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel4.add(btnMAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 240, 100));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 830, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMenuE.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 920, 540));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 874, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcion para salir
    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    //Cambia el color de la x en el header
    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red); //Cambia el color del fondo
        exitTxt.setForeground(Color.white); //Cambia el color del 
    }//GEN-LAST:event_exitTxtMouseEntered

    /**
     * Metodo que cambia de color de la x de exit cuando pierde el foco
     */
    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white); //Cambia el color del fondo
        exitTxt.setForeground(Color.black); //Cambia el color del 
    }//GEN-LAST:event_exitTxtMouseExited

    /**
     * Metodo que mueve el JFrame
     * @param evt evento
     */
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen(); //Toma el valor de la posicion en x
        int y = evt.getYOnScreen(); //Toma el valor de la posicion en y
        this.setLocation(x - xMouse, y - yMouse); //Cambia el valor de la posición de la ventana
    }//GEN-LAST:event_headerMouseDragged

    /**
     * Metodo para obtener la posicion del panel
     * @param evt evento
     */
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX(); //Obtiene la posicion de en x del panel
        yMouse = evt.getY(); //Obtiene la posicion de en y del panel
    }//GEN-LAST:event_headerMousePressed

    //Metodo que cambia el color del texto cuando pierde el foco
    private void txtBtnBuddyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnBuddyMouseExited
        btnBuddy.setBackground(new Color(37, 150, 190));//Cambia el color del fondo
    }//GEN-LAST:event_txtBtnBuddyMouseExited

    //Metodo que cambia el color del texto cuando gana el foco
    private void txtBtnBuddyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnBuddyMouseEntered
        btnBuddy.setBackground(new Color(146, 203, 223)); //Cambia el color del fondo
    }//GEN-LAST:event_txtBtnBuddyMouseEntered

    //Metodo que va al menú correspondiente al boton
    private void txtBtnBuddyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnBuddyMouseClicked
        //this.dispose(); //Cierra la ventana
        Tree T = new Tree();
       new Interfaz(T).setVisible(true);
    }//GEN-LAST:event_txtBtnBuddyMouseClicked

     //Metodo que va al menú correspondiente al boton
    private void txtBtnMajusteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnMajusteMouseClicked
        //this.dispose(); //Cierra la ventana
        ListaSentinelaMejor L = new ListaSentinelaMejor();
        new InterfazMejor(L).setVisible(true);
    }//GEN-LAST:event_txtBtnMajusteMouseClicked

    //Metodo que cambia el color del texto cuando gana el foco
    private void txtBtnMajusteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnMajusteMouseEntered
        btnMAjuste.setBackground(new Color(146, 203, 223)); //Cambia el color del fondo
    }//GEN-LAST:event_txtBtnMajusteMouseEntered

    //Metodo que cambia el color del texto cuando pierde el foco
    private void txtBtnMajusteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnMajusteMouseExited
        btnMAjuste.setBackground(new Color(37, 150, 190));//Cambia el color del fondo
    }//GEN-LAST:event_txtBtnMajusteMouseExited



    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * JPanel para el boton
    */
    private javax.swing.JPanel btnBuddy;
    /**
    * JPanel para el boton
    */
    private javax.swing.JPanel btnMAjuste;
    /**
    * Panel del boton de exit
    */
    private javax.swing.JPanel exitBtn;
    /**
    * JLabel que representa el boton de exit
    */
    private javax.swing.JLabel exitTxt;
    /**
    * Panel del header
    *
    */
    private javax.swing.JPanel header;
    /**
    * JLable de imagen
    */
    private javax.swing.JLabel jLabel1;
    /**
    * JLabel de titulo
    */
    private javax.swing.JLabel jLabel3;
    /**
    * JLabel de titulo
    */
    private javax.swing.JLabel jLabel4;
    /**
    * Panel Principal
    */
    private javax.swing.JPanel jPanel2;
    /**
    * Panel Secundario
    */
    private javax.swing.JPanel jPanel4;
    /**
    * JLabel para el boton
    *
    */
    private javax.swing.JLabel txtBtnBuddy;
    /**
    * JLabel para el boton
    *
    */
    private javax.swing.JLabel txtBtnMajuste;
    // End of variables declaration//GEN-END:variables
}
